development:
  adapter: postgresql
  encoding: unicode
  database: leveredge_development
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: leveredge_test
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: leveredge_production
